services:
  api:
    image: ids_img:latest
    network_mode: "host"
    volumes:
      - ./api:/app
    environment:
      - ADMIN_PASS=secreto
      - DB_USER=root 
      - DB_PASS=my-secret-pw
      - DB_PORT=3306
      - DB_IP=localhost
    command: sh -c ". .venv/bin/activate && python3 app/app.py"

  web:
    image: ids_img:latest
    network_mode: "host"
    environment:
      - API_URL=http://localhost:5000
    volumes:
      - ./web:/app
    command: sh -c ". .venv/bin/activate && python3 app/app.py"
